config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :businesses
  devise_for :admins
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, shallow: true do
    resources :communicates
    resources :bad_reports
  end

  resources :businesses, shallow: true do
    resources :shops
    resources :communicates
  end

  resources :shops, shallow: true do
    resources :users
    resources :communicates
    resources :bad_reports
  end
end

app/models/bad_report.rb
class BadReport < ApplicationRecord
  belongs_to :user
  belongs_to :communicate
end

app/controllers/bad_reports_controller.rb
class BadReportsController < ApplicationController
  before_action :set_bad_report, only: [:show, :edit, :update, :destroy]

  # GET /bad_reports
  # GET /bad_reports.json
  def index
    @bad_reports = BadReport.all
  end

  # GET /bad_reports/1
  # GET /bad_reports/1.json
  def show
  end

  # GET /bad_reports/new
  def new
    @bad_report = BadReport.new
  end

  # GET /bad_reports/1/edit
  def edit
  end

  # POST /bad_reports
  # POST /bad_reports.json
  def create
    @bad_report = BadReport.new(bad_report_params)

    respond_to do |format|
      if @bad_report.save
        format.html { redirect_to @bad_report, notice: 'Bad report was successfully created.' }
        format.json { render :show, status: :created, location: @bad_report }
      else
        format.html { render :new }
        format.json { render json: @bad_report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bad_reports/1
  # PATCH/PUT /bad_reports/1.json
  def update
    respond_to do |format|
      if @bad_report.update(bad_report_params)
        format.html { redirect_to @bad_report, notice: 'Bad report was successfully updated.' }
        format.json { render :show, status: :ok, location: @bad_report }
      else
        format.html { render :edit }
        format.json { render json: @bad_report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bad_reports/1
  # DELETE /bad_reports/1.json
  def destroy
    @bad_report.destroy
    respond_to do |format|
      format.html { redirect_to bad_reports_url, notice: 'Bad report was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bad_report
      @bad_report = BadReport.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def bad_report_params
      params.fetch(:bad_report, {})
    end
end

app/helpers/bad_reports_helper.rb
module BadReportsHelper
end

app/views/bad_reports/_form.html.erb
<%= form_with(model: bad_report, local: true) do |form| %>
  <% if bad_report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bad_report.errors.count, "error") %> prohibited this bad_report from being saved:</h2>

      <ul>
        <% bad_report.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/bad_reports/edit.html.erb
<h1>Editing Bad Report</h1>

<%= render 'form', bad_report: @bad_report %>

<%= link_to 'Show', @bad_report %> |
<%= link_to 'Back', bad_reports_path %>

app/views/bad_reports/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bad Reports</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bad_reports.each do |bad_report| %>
      <tr>
        <td><%= link_to 'Show', bad_report %></td>
        <td><%= link_to 'Edit', edit_bad_report_path(bad_report) %></td>
        <td><%= link_to 'Destroy', bad_report, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bad Report', new_bad_report_path %>

app/views/bad_reports/new.html.erb
<h1>New Bad Report</h1>

<%= render 'form', bad_report: @bad_report %>

<%= link_to 'Back', bad_reports_path %>

app/views/bad_reports/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_bad_report_path(@bad_report) %> |
<%= link_to 'Back', bad_reports_path %>