config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :businesses
  devise_for :admins
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, shallow: true do
    resources :communicates
    resources :bad_reports
  end

  resources :businesses, shallow: true do
    resources :shops
    resources :communicates
  end

  resources :shops, shallow: true do
    resources :users
    resources :communicates
    resources :bad_reports
  end
end

app/models/communicate.rb
class Communicate < ApplicationRecord
  belongs_to :user
  belongs_to :shop
  has_many :bad_reports
end

app/controllers/communicates_controller.rb
class CommunicatesController < ApplicationController
  before_action :set_communicate, only: [:show, :edit, :update, :destroy]

  # GET /communicates
  # GET /communicates.json
  def index
    @communicates = Communicate.all
  end

  # GET /communicates/1
  # GET /communicates/1.json
  def show
  end

  # GET /communicates/new
  def new
    @communicate = Communicate.new
  end

  # GET /communicates/1/edit
  def edit
  end

  # POST /communicates
  # POST /communicates.json
  def create
    @communicate = Communicate.new(communicate_params)

    respond_to do |format|
      if @communicate.save
        format.html { redirect_to @communicate, notice: 'Communicate was successfully created.' }
        format.json { render :show, status: :created, location: @communicate }
      else
        format.html { render :new }
        format.json { render json: @communicate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /communicates/1
  # PATCH/PUT /communicates/1.json
  def update
    respond_to do |format|
      if @communicate.update(communicate_params)
        format.html { redirect_to @communicate, notice: 'Communicate was successfully updated.' }
        format.json { render :show, status: :ok, location: @communicate }
      else
        format.html { render :edit }
        format.json { render json: @communicate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /communicates/1
  # DELETE /communicates/1.json
  def destroy
    @communicate.destroy
    respond_to do |format|
      format.html { redirect_to communicates_url, notice: 'Communicate was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_communicate
      @communicate = Communicate.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def communicate_params
      params.fetch(:communicate, {})
    end
end

app/helpers/communicates_helper.rb
module CommunicatesHelper
end

app/views/communicates/_form.html.erb
<%= form_with(model: communicate, local: true) do |form| %>
  <% if communicate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(communicate.errors.count, "error") %> prohibited this communicate from being saved:</h2>

      <ul>
        <% communicate.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/communicates/edit.html.erb
<h1>Editing Communicate</h1>

<%= render 'form', communicate: @communicate %>

<%= link_to 'Show', @communicate %> |
<%= link_to 'Back', communicates_path %>

app/views/communicates/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Communicates</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @communicates.each do |communicate| %>
      <tr>
        <td><%= link_to 'Show', communicate %></td>
        <td><%= link_to 'Edit', edit_communicate_path(communicate) %></td>
        <td><%= link_to 'Destroy', communicate, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Communicate', new_communicate_path %>

app/views/communicates/new.html.erb
<h1>New Communicate</h1>

<%= render 'form', communicate: @communicate %>

<%= link_to 'Back', communicates_path %>

app/views/communicates/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_communicate_path(@communicate) %> |
<%= link_to 'Back', communicates_path %>